# Generated by Django 2.0.8 on 2018-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.CharField(default='Recent Posts', max_length=255),
        ),
    ]
